const ALLOWED_ORIGINS = new Set(["https://ash-fall.com", "https://www.ash-fall.com"]);
const SESSION_TTL = 60 * 60 * 24 * 30;
const PBKDF2_ITERATIONS = 120000;
const getOrigin = r => { const o=r.headers.get("Origin"); return ALLOWED_ORIGINS.has(o)?o:"https://ash-fall.com"; };
const json=(data,status=200,origin="https://ash-fall.com",extra={})=>new Response(JSON.stringify(data),{status,headers:{"content-type":"application/json; charset=UTF-8","access-control-allow-origin":origin,"access-control-allow-credentials":"true","access-control-allow-methods":"GET,POST,PUT,OPTIONS","access-control-allow-headers":"content-type, authorization","cache-control":"no-store",...extra}});
const text=(v,max)=>typeof v==="string"&&v.trim().length>0&&v.trim().length<=max;
const email=v=>typeof v==="string"?v.trim().toLowerCase():""; const username=v=>typeof v==="string"?v.trim().toLowerCase():"";
const makeId=()=>crypto.randomUUID();
const b64=b=>btoa(String.fromCharCode(...b)); const unb64=s=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));
async function hashPassword(p){const salt=crypto.getRandomValues(new Uint8Array(16)),key=await crypto.subtle.importKey("raw",new TextEncoder().encode(p),"PBKDF2",false,["deriveBits"]),bits=await crypto.subtle.deriveBits({name:"PBKDF2",salt,iterations:PBKDF2_ITERATIONS,hash:"SHA-256"},key,256);return `pbkdf2-sha256$${PBKDF2_ITERATIONS}$${b64(salt)}$${b64(new Uint8Array(bits))}`}
async function verifyPassword(p,s){const a=s.split("$");if(a.length!==4||a[0]!=="pbkdf2-sha256")return false;const n=Number(a[1]);if(!Number.isInteger(n)||n<100000||n>1000000)return false;const key=await crypto.subtle.importKey("raw",new TextEncoder().encode(p),"PBKDF2",false,["deriveBits"]),bits=await crypto.subtle.deriveBits({name:"PBKDF2",salt:unb64(a[2]),iterations:n,hash:"SHA-256"},key,256),x=new Uint8Array(bits),y=unb64(a[3]);if(x.length!==y.length)return false;let d=0;for(let i=0;i<x.length;i++)d|=x[i]^y[i];return d===0}
const setCookie=t=>`knightfall_session=${encodeURIComponent(t)}; Max-Age=${SESSION_TTL}; Path=/; HttpOnly; Secure; SameSite=Lax`; const clearCookie="knightfall_session=; Max-Age=0; Path=/; HttpOnly; Secure; SameSite=Lax";
function sessionToken(r){const m=(r.headers.get("Cookie")||"").match(/(?:^|;\s*)knightfall_session=([^;]+)/);return m?decodeURIComponent(m[1]):null}
async function currentUser(r,e){const t=sessionToken(r);if(!t)return null;const s=await e.SESSIONS.get(`session:${t}`,"json");if(!s?.userId)return null;return e.DB.prepare("SELECT id,username,email,display_name,role,bio,avatar_url,website_url,location,pronouns,created_at FROM users WHERE id=?").bind(s.userId).first()}
const publicUser=u=>({id:u.id,username:u.username,email:u.email,display_name:u.display_name,role:u.role,bio:u.bio||"",avatar_url:u.avatar_url||"",website_url:u.website_url||"",location:u.location||"",pronouns:u.pronouns||"",created_at:u.created_at});
async function newSession(uid,e){const t=`${makeId()}${makeId().replaceAll("-","")}`;await e.SESSIONS.put(`session:${t}`,JSON.stringify({userId:uid}),{expirationTtl:SESSION_TTL});return t}
const safeUrl=v=>{if(!v)return true;try{const u=new URL(v);return u.protocol==="https:"||u.protocol==="http:"}catch{return false}};
export default {async fetch(r,e){const o=getOrigin(r),u=new URL(r.url);if(r.method==="OPTIONS")return new Response(null,{status:204,headers:{"access-control-allow-origin":o,"access-control-allow-credentials":"true","access-control-allow-methods":"GET,POST,PUT,OPTIONS","access-control-allow-headers":"content-type, authorization","access-control-max-age":"86400"}});try{
if(u.pathname==="/health"&&r.method==="GET"){const c=await e.DB.prepare("SELECT 1 AS ok").first();return json({ok:c?.ok===1,service:"knightfall-api",database:true,sessions:true},200,o)}
if(u.pathname==="/api/auth/register"&&r.method==="POST"){let b;try{b=await r.json()}catch{return json({error:"Request body must be valid JSON."},400,o)}const un=username(b.username),em=email(b.email),dn=typeof b.display_name==="string"&&b.display_name.trim()?b.display_name.trim():un,p=typeof b.password==="string"?b.password:"";if(!/^[a-z0-9_]{3,24}$/.test(un))return json({error:"Username must be 3-24 characters using letters, numbers, or underscores."},400,o);if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(em)||em.length>254)return json({error:"Please provide a valid email address."},400,o);if(p.length<12||p.length>128)return json({error:"Password must be 12-128 characters."},400,o);if(!text(dn,60))return json({error:"Display name must be 1-60 characters."},400,o);if(await e.DB.prepare("SELECT id FROM users WHERE username=? OR email=? LIMIT 1").bind(un,em).first())return json({error:"That username or email is already registered."},409,o);const ph=await hashPassword(p),ins=await e.DB.prepare("INSERT INTO users (username,email,password_hash,display_name) VALUES (?,?,?,?)").bind(un,em,ph,dn).run(),usr=await e.DB.prepare("SELECT id,username,email,display_name,role,bio,avatar_url,website_url,location,pronouns,created_at FROM users WHERE id=?").bind(ins.meta.last_row_id).first(),tok=await newSession(usr.id,e);return json({user:publicUser(usr)},201,o,{"set-cookie":setCookie(tok)})}
if(u.pathname==="/api/auth/login"&&r.method==="POST"){let b;try{b=await r.json()}catch{return json({error:"Request body must be valid JSON."},400,o)}const ident=typeof b.identifier==="string"?b.identifier.trim().toLowerCase():"",p=typeof b.password==="string"?b.password:"",usr=await e.DB.prepare("SELECT id,username,email,password_hash,display_name,role,bio,avatar_url,website_url,location,pronouns,created_at FROM users WHERE username=? OR email=? LIMIT 1").bind(ident,ident).first();if(!ident||!p||!usr||!(await verifyPassword(p,usr.password_hash)))return json({error:"Invalid username/email or password."},401,o);return json({user:publicUser(usr)},200,o,{"set-cookie":setCookie(await newSession(usr.id,e))})}
if(u.pathname==="/api/auth/me"&&r.method==="GET"){const usr=await currentUser(r,e);return usr?json({authenticated:true,user:publicUser(usr)},200,o):json({authenticated:false},200,o)}
if(u.pathname==="/api/auth/logout"&&r.method==="POST"){const t=sessionToken(r);if(t)await e.SESSIONS.delete(`session:${t}`);return json({ok:true},200,o,{"set-cookie":clearCookie})}
const pm=u.pathname.match(/^\/api\/users\/([^/]+)$/);if(pm&&r.method==="GET"){const usr=await e.DB.prepare("SELECT id,username,display_name,role,bio,avatar_url,website_url,location,pronouns,created_at FROM users WHERE username=?").bind(username(decodeURIComponent(pm[1]))).first();return usr?json({user:usr},200,o):json({error:"Profile not found."},404,o)}
if(u.pathname==="/api/members"&&r.method==="GET"){const limit=Math.min(Math.max(Number(u.searchParams.get("limit")||50),1),100),{results}=await e.DB.prepare("SELECT id,username,display_name,role,bio,avatar_url,created_at FROM users ORDER BY created_at DESC LIMIT ?").bind(limit).all();return json({users:results},200,o)}
if(u.pathname==="/api/profile"&&r.method==="PUT"){const usr=await currentUser(r,e);if(!usr)return json({error:"Authentication required."},401,o);let b;try{b=await r.json()}catch{return json({error:"Request body must be valid JSON."},400,o)}const p={display_name:typeof b.display_name==="string"?b.display_name.trim():"",bio:typeof b.bio==="string"?b.bio.trim():"",avatar_url:typeof b.avatar_url==="string"?b.avatar_url.trim():"",website_url:typeof b.website_url==="string"?b.website_url.trim():"",location:typeof b.location==="string"?b.location.trim():"",pronouns:typeof b.pronouns==="string"?b.pronouns.trim():""};if(!text(p.display_name,60)||p.bio.length>1000||p.location.length>100||p.pronouns.length>60||!safeUrl(p.avatar_url)||!safeUrl(p.website_url))return json({error:"Invalid profile data."},400,o);await e.DB.prepare("UPDATE users SET display_name=?,bio=?,avatar_url=?,website_url=?,location=?,pronouns=?,updated_profile_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(p.display_name,p.bio,p.avatar_url,p.website_url,p.location,p.pronouns,usr.id).run();return json({user:publicUser(await currentUser(r,e))},200,o)}
if(u.pathname==="/api/categories"&&r.method==="GET"){const {results}=await e.DB.prepare("SELECT id,name,slug,description,sort_order FROM categories ORDER BY sort_order ASC,name ASC").all();return json({categories:results},200,o)}
if(u.pathname==="/api/threads"&&r.method==="GET"){const cid=Number(u.searchParams.get("category_id")),limit=Math.min(Math.max(Number(u.searchParams.get("limit")||25),1),50),base="SELECT t.id,t.title,t.slug,t.category_id,c.name AS category_name,t.user_id,u.display_name AS author_name,t.pinned,t.locked,t.views,t.created_at,t.updated_at,COUNT(p.id) AS reply_count FROM threads t JOIN categories c ON c.id=t.category_id JOIN users u ON u.id=t.user_id LEFT JOIN posts p ON p.thread_id=t.id",q=Number.isInteger(cid)&&cid>0?e.DB.prepare(`${base} WHERE t.category_id=? GROUP BY t.id ORDER BY t.pinned DESC,t.updated_at DESC LIMIT ?`).bind(cid,limit):e.DB.prepare(`${base} GROUP BY t.id ORDER BY t.pinned DESC,t.updated_at DESC LIMIT ?`).bind(limit),{results}=await q.all();return json({threads:results},200,o)}
if(u.pathname==="/api/threads"&&r.method==="POST"){const usr=await currentUser(r,e);if(!usr)return json({error:"Authentication required."},401,o);let b;try{b=await r.json()}catch{return json({error:"Request body must be valid JSON."},400,o)}const cid=Number(b.category_id);if(!text(b.title,160)||!text(b.body,20000)||!Number.isInteger(cid)||cid<1)return json({error:"A valid title, body, and category are required."},400,o);if(!(await e.DB.prepare("SELECT id FROM categories WHERE id=?").bind(cid).first()))return json({error:"Category not found."},404,o);const slugBase=b.title.trim().toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,80)||"thread",slug=`${slugBase}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,7)}`,ins=await e.DB.prepare("INSERT INTO threads (category_id,user_id,title,slug,body) VALUES (?,?,?,?,?)").bind(cid,usr.id,b.title.trim(),slug,b.body.trim()).run();return json({id:ins.meta.last_row_id,slug},201,o)}
const tm=u.pathname.match(/^\/api\/threads\/(\d+)$/);if(tm&&r.method==="GET"){const tid=Number(tm[1]),th=await e.DB.prepare("SELECT t.id,t.title,t.slug,t.category_id,c.name AS category_name,t.user_id,u.display_name AS author_name,t.body,t.pinned,t.locked,t.views,t.created_at,t.updated_at FROM threads t JOIN categories c ON c.id=t.category_id JOIN users u ON u.id=t.user_id WHERE t.id=?").bind(tid).first();if(!th)return json({error:"Thread not found."},404,o);await e.DB.prepare("UPDATE threads SET views=views+1 WHERE id=?").bind(tid).run();const {results:posts}=await e.DB.prepare("SELECT p.id,p.thread_id,p.user_id,u.username,u.display_name AS author_name,u.avatar_url,p.body,p.created_at,p.updated_at FROM posts p JOIN users u ON u.id=p.user_id WHERE p.thread_id=? ORDER BY p.created_at ASC").bind(tid).all();return json({thread:{...th,views:Number(th.views||0)+1},posts},200,o)}
if(tm&&r.method==="POST"){const usr=await currentUser(r,e);if(!usr)return json({error:"Authentication required."},401,o);let b;try{b=await r.json()}catch{return json({error:"Request body must be valid JSON."},400,o)}const tid=Number(tm[1]);const th=await e.DB.prepare("SELECT id,locked FROM threads WHERE id=?").bind(tid).first();if(!th)return json({error:"Thread not found."},404,o);if(th.locked)return json({error:"This thread is locked."},403,o);if(!text(b.body,20000))return json({error:"Reply body is required."},400,o);const ins=await e.DB.prepare("INSERT INTO posts (thread_id,user_id,body) VALUES (?,?,?)").bind(tid,usr.id,b.body.trim()).run();await e.DB.prepare("UPDATE threads SET updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(tid).run();return json({id:ins.meta.last_row_id},201,o)}
return json({error:"Not found"},404,o)}catch(err){console.error(err);return json({error:"Internal server error"},500,o)}}};
